### ISSUE TITLE
Flash/Debug STM32 from devcontainer

### ISSUE THREAD

**Issue by kaizoku-oh** [embeddedcontainers/zephyr#7]
Hello,
did anyone manage to flash an STM32 board from a devcontainer environment
It seems like the docker image is missing STM32CubeProgrammer (I don't know if that's supposed to come with zephyr toolchain or it should be installed separately)
I'd be happy to contribute.
Thanks in advance.

![image](https://github.com/embeddedcontainers/zephyr/assets/22129291/3abf74c4-525a-4353-bd9d-d642fea9729e)

**Comment by arifbalik** [comment]
I'm pretty sure it does not come with the container, it is quite challenging to download ST software from headless machines since ST requires login and EULA. This one is a dirty solution but I've installed it using on a different machine with similar setup + GUI and then moved the binaries to the container

**Comment by kaizoku-oh** [comment]
Yes, I agree STM32CubeProgrammer download and install is not straight forward and I shoud figure out a way to install it on the container by just moving a local copy of the installation to specific directories in the container.

**Comment by kaizoku-oh** [comment]
And how about debugging from inside the vscode devcontainer?
Since the debugger uses `ST-LINK_gdbserver` which is a tool part of the STM32CubeIDE installation, I guess I should find a way to also copy that tool to the container with its dependencis.
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "cwd": "${workspaceFolder}",
            "executable": "${workspaceFolder}/app/build/zephyr/zephyr.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "stlink",
            // This one
            "stlinkPath": "/opt/st/stm32cubeide_1.14.0/plugins/com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.linux64_2.1.100.202310302101/tools/bin/ST-LINK_gdbserver",
            "device": "STM32U575ZI",
            "interface": "swd",
            "runToEntryPoint": "main",
            "preLaunchTask": "Build (application)",
            "gdbPath": "${userHome}/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb",
            "armToolchainPath": "${userHome}/zephyr-sdk-0.16.4/arm-zephyr-eabi/arm-zephyr-eabi/bin",
        }
    ]
}

```

**Comment by arifbalik** [comment]
I haven't used STCubeProgrammer to debug anything yet. I just opened an OpenOCD server on my host and connected to it with gdb and vscode cortex-debug plugin I think. It was a long time ago so I don't remember specifics but I do have my launch.json file;

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote STM32",
            "cwd": "${workspaceRoot}",
            "executable": "./build/zephyr/zephyr.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "external",
            "gdbTarget": "192.168.1.123:3333",
            "device": "STM32F0xx",
            "runToEntryPoint": "main", 
            "svdFile": "./esdc8034/boards/arm/esdc8034/stm32f030.svd",
            "showDevDebugOutput": "raw",
            "preLaunchTask": "build_ecool_app",
            "preLaunchCommands": [
                "monitor reset halt",
                "monitor stm32f0x unlock 0",
                "monitor stm32f0x mass_erase 0",
                "monitor program C:/Users/arifb/build/zephyr/zephyr.elf verify reset"
            ],
           
        }
    ]
}
```

**Comment by aniltirli** [comment]
i am able to debug stm32 with devcontainer in vscode and use editor to step by step debug, i haven't tried to use docker images in this repo but i used `ghcr.io/zephyrproject-rtos/ci:latest` docker image (<https://github.com/zephyrproject-rtos/docker-image>) as base, vscode extension `marus25.cortex-debug` and openocd comes within the docker image, you don't need ST IDE here. required toolchain comes with the docker image

devcontainer.json 

```
{
	"name": "zephyr-template",
	"image": "ghcr.io/zephyrproject-rtos/ci:latest",
    "workspaceMount": "source=${localEnv:HOME}/projects/zephyr-stm32,target=/workdir,type=bind,consistency=cached",
    "workspaceFolder": "/workdir",
	"runArgs": [
        "--device", "/dev/bus/usb/"
    ],
	"postCreateCommand": "west init zephyrproject/ && cd zephyrproject/ && west update",
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-vscode.cpptools-extension-pack",
				"marus25.cortex-debug"
			]
		}
	}
}
```

launch.json

```
{
    "configurations": [
    {
        "cwd": "${workspaceRoot}/<application_folder>",
        "executable": "build/zephyr/zephyr.elf",
        "name": "Debug with OpenOCD",
        "request": "launch",
        "type": "cortex-debug",
        "serverpath": "/opt/toolchains/zephyr-sdk-0.16.4/sysroots/x86_64-pokysdk-linux/usr/bin/openocd",
        "servertype": "openocd",
        "searchDir": [],
        "runToEntryPoint": "main",
        "device": "<device_name>",
        "showDevDebugOutput": "none",
        "configFiles": [
         "/workdir/zephyrproject/zephyr/boards/arm/<device_name>/support/openocd.cfg"
        ]
    }
    ]
}
```

settings.json

```
{
    "cortex-debug.armToolchainPath": "/opt/toolchains/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/",
    "cortex-debug.armToolchainPrefix": "arm-zephyr-eabi",
    "files.associations": {
        "locale": "c",
        "pwm.h": "c",
        "typeinfo": "c",
        "stm32_ll_bus.h": "c"
    },
    "cmake.sourceDirectory": "/workdir/<application_folder>"
}
```

**Comment by kaizoku-oh** [comment]
> i am able to debug stm32 with devcontainer in vscode and use editor to step by step debug, i haven't tried to use docker images in this repo but i used `ghcr.io/zephyrproject-rtos/ci:latest` docker image (https://github.com/zephyrproject-rtos/docker-image) as base, vscode extension `marus25.cortex-debug` and openocd comes within the docker image, you don't need ST IDE here. required toolchain comes with the docker image
> 
> devcontainer.json
> 
> ```
> {
> 	"name": "zephyr-template",
> 	"image": "ghcr.io/zephyrproject-rtos/ci:latest",
>     "workspaceMount": "source=${localEnv:HOME}/projects/zephyr-stm32,target=/workdir,type=bind,consistency=cached",
>     "workspaceFolder": "/workdir",
> 	"runArgs": [
>         "--device", "/dev/bus/usb/"
>     ],
> 	"postCreateCommand": "west init zephyrproject/ && cd zephyrproject/ && west update",
> 	"customizations": {
> 		"vscode": {
> 			"extensions": [
> 				"ms-vscode.cpptools-extension-pack",
> 				"marus25.cortex-debug"
> 			]
> 		}
> 	}
> }
> ```
> 
> launch.json
> 
> ```
> {
>     "configurations": [
>     {
>         "cwd": "${workspaceRoot}/<application_folder>",
>         "executable": "build/zephyr/zephyr.elf",
>         "name": "Debug with OpenOCD",
>         "request": "launch",
>         "type": "cortex-debug",
>         "serverpath": "/opt/toolchains/zephyr-sdk-0.16.4/sysroots/x86_64-pokysdk-linux/usr/bin/openocd",
>         "servertype": "openocd",
>         "searchDir": [],
>         "runToEntryPoint": "main",
>         "device": "<device_name>",
>         "showDevDebugOutput": "none",
>         "configFiles": [
>          "/workdir/zephyrproject/zephyr/boards/arm/<device_name>/support/openocd.cfg"
>         ]
>     }
>     ]
> }
> ```
> 
> settings.json
> 
> ```
> {
>     "cortex-debug.armToolchainPath": "/opt/toolchains/zephyr-sdk-0.16.4/arm-zephyr-eabi/bin/",
>     "cortex-debug.armToolchainPrefix": "arm-zephyr-eabi",
>     "files.associations": {
>         "locale": "c",
>         "pwm.h": "c",
>         "typeinfo": "c",
>         "stm32_ll_bus.h": "c"
>     },
>     "cmake.sourceDirectory": "/workdir/<application_folder>"
> }
> ```

I practically did the same, here is my repo: https://github.com/kaizoku-oh/zephyr-online-workspace
